<?php

namespace imie\ComplogBundle\Repository;

/**
 * CustOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
