<?php

namespace imie\ComplogBundle\Entity;

/**
 * CustOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
