<?php

namespace imie\ComplogBundle\Repository;

/**
 * CustOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustOrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return string
     */
    public function getNextRef(){

        $invoice = $this->findOneBy(
            array(),
            array('id' => 'DESC')
        );
        $lastRef = $invoice->getRef();
        $lastNumber = preg_replace("/[^0-9]/", '', $lastRef);

        $nextNumber = (int)$lastNumber + 1;
        $nextRef = 'ORDE' . (string)$nextNumber;

        return $nextRef;
    }
}
