<?php

namespace imie\ComplogBundle\Entity;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
